version: '3.5'

services:       
    sonar:
      image: sonar-latest


      deploy:
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s 
      ports:
          - "7000:9000"
    
         
networks:
  default:
    external:
      name: nat
      
